name: ModernTeleport
version: '${project.version}'
main: dev.betrix.modernteleport.ModernTeleport
api-version: 1.19
commands:
  tprequest:
    description: "Send a teleport request to a player"
    usage: "/<command> PLAYER_NAME"
    aliases:
      - tpa
  tpaccept:
    description: "Accept an incoming teleport request"
    usage: /<command>
  tpreject:
    description: "Reject an incoming teleport request"
    usage: /<command>